spring.application.name=cashflow-account-service


spring.datasource.url =jdbc:mysql://localhost:3306/cashflow
spring.datasource.username=root
spring.datasource.password=Reshma@1234



spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


transaction.service.url =http://localhost:8080

jwt.public-key= classpath:keys/public_key.pem

server.servlet.context-path=/cashflow-account-service

